### ISSUE TITLE
Issue with missing screenshot folder

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/working-with-jquery#1]
Hey @thomasjbradley

I know we're not really doing the javaScript course anymore, but I still want to lean it so I'm going to try and keep up with it :)

I've completed everything in week 3 of the course, even the quiz (I have a screen shot lol), but I ran into an issue. For the in-class assignment 'working with jQuery', when I run it through Markbot it says it's missing a screenshot folder that didn't come with the fork, and to include a linked font that wasn't in the follow-along lesson. What should I do to fix that?

Thanks!
Jess

<img width="1680" alt="Screen Shot 2020-03-17 at 10 02 29 AM" src="https://user-images.githubusercontent.com/43217543/76879519-bdd6de00-684c-11ea-9112-7d7e72a8edf6.png">

**Comment by thomasjbradley** [comment]
It’s fixed up now. You’ll have to go to the original repo and copy the the 2 `.markbot` files & the screenshots folder.
https://github.com/acgd-webdev-javascript/working-with-jquery
